// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaServicios.Api.ShoppingCart.Persistence;

#nullable disable

namespace TiendaServicios.Api.ShoppingCart.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20240614200130_Initial-Migration-MySql")]
    partial class InitialMigrationMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TiendaServicios.Api.ShoppingCart.Model.CartDetail", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CartSessionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedProduct")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CartSessionId");

                    b.ToTable("ShoppingCartDetail");
                });

            modelBuilder.Entity("TiendaServicios.Api.ShoppingCart.Model.CartSession", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCartSession");
                });

            modelBuilder.Entity("TiendaServicios.Api.ShoppingCart.Model.CartDetail", b =>
                {
                    b.HasOne("TiendaServicios.Api.ShoppingCart.Model.CartSession", "CartSession")
                        .WithMany("Products")
                        .HasForeignKey("CartSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartSession");
                });

            modelBuilder.Entity("TiendaServicios.Api.ShoppingCart.Model.CartSession", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
